### ISSUE TITLE
Include the pynautobot version in the User-Agent header by default

### ISSUE THREAD

**Issue by nrnvgh** [nautobot/pynautobot#205] opened 2024-07-03 20:05 UTC
We ran into a case recently where it would have been useful to have pynautobot send its version in a user-agent header (or similar) by default; something like: `python-pynautobot/1.5.2`.  For example, this would allow us to reach out to specific users and let them know they can/should upgrade to a more recent version. I'm thinking a patch like this:

```diff
--- a/pynautobot/core/api.py
+++ b/pynautobot/core/api.py
@@ -19,6 +19,7 @@ import requests
 from requests.adapters import HTTPAdapter
 from urllib3 import Retry

+import pynautobot
 from pynautobot.core.query import Request
 from pynautobot.core.app import App, PluginsApp
 from pynautobot.core.graphql import GraphQLQuery
@@ -83,6 +84,9 @@ class Api(object):
         self.base_url = base_url
         self.http_session = requests.Session()
         self.http_session.verify = verify
+        self.http_session.headers.update(
+            {"User-Agent": f"python-pynautobot/{pynautobot.__version__}"}
+        )
         if retries:
             _adapter = HTTPAdapter(
                 max_retries=Retry(
```

...which applies cleanly against both the `ltm-1.6` and `develop` branches. Thoughts? I'm happy to fork and submit PRs for either or both branches if this works for you. If it does, would you accept it into the LTM branch or is this purely a 2.x thing? It's obviously not a bugfix, but as we're still on nautobot 1.6, I gotta ask. I could also extend the header to include the python-requests version as well if that would be useful.

**Comment by joewesch** [comment] 2024-07-03 21:02
This looks like a duplicate of #199. It was noted in that issue that this is already possible by setting the header after instantiation, but I can understand the desire to not need an extra step.

> If it does, would you accept it into the LTM branch or is this purely a 2.x thing? It's obviously not a bugfix, but as we're still on nautobot 1.6, I gotta ask.

Yes, that seems like an acceptable low-risk change to me if you're willing to do the leg work.

**Comment by nrnvgh** [comment] 2024-07-03 21:42
Submitted:
- PR #206 (ltm-1.6)
- PR #207 (develop)

**Comment by nrnvgh** [comment] 2024-07-04 22:34
> This looks like a duplicate of #199. It was noted in that issue that this is already possible by setting the header after instantiation, but I can understand the desire to not need an extra step.

Also, in our case, we have a large (and unknown. and ever-changing.) number of folks who are writing pynautobot-enabled scripts to access our data, and asking everyone to update their code to send the pynautobot version in the useragent is... impractical. =)

**Comment by nrnvgh** [comment] 2024-07-05 16:58
I see the failure in the PR #206 ; is that a 'me' problem or a 'pipeline' problem? The test harness passes locally for me, modulo a `DeprecationWarning` for something outside of the pynautobot tree entirely.

**Comment by nrnvgh** [comment] 2024-07-05 21:41
I dug into this and, with a help from Slack, was ultimately able to trace this to an issue where `__version__` doesn't get set in `pynautobot/__init__.py` when running under Docker. Under docker, package information for `pynautobot` is not available (the package isn't installed). Per suggestion from @jvanderaa, I've updated `__init__.py` in both my PR's so that if the package isn't found, set `__version__` to something informative.

**Comment by nrnvgh** [comment] 2024-08-01 23:21
Both PRs have been merged; AFAIC this can be closed, with my thanks.

**Comment by joewesch** [comment] 2024-08-02 12:58
Thanks!

**Closed by joewesch** 2024-08-02 12:58 UTC
