### ISSUE TITLE
500 Server Error whent trying to add memeber to virtual-chassis

### ISSUE THREAD

**Issue by lvrfrc87** [nautobot/pynautobot#31] opened 2022-02-02 10:58 UTC
When I try to add an existing device in Nuatobot to an existing virtual-chassis via Ansible `networktocode.nautobot.device` module I get `500 Server Error`.
I have tried to do the same via Postman and worked work as expected while with `pynautobot` I get the above error.

The playbook I am using, was working as expected with a previous version of nautobot/ansible/pynautobot. Unfortunately I am not able to tell on which versions they were.

pynautobot version:
```
(venv) [root@ou01ap2x pb_nautobot_device_onboarding]# pip3 list | grep pynautobot
pynautobot         1.0.4
```

pynautobot error:
```
>>> my_device.virtual_chassis="4ed8258a-60f4-4a47-89eb-c3e513224631"
>>> my_device.vc_position=1
>>> my_device.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/git/pb_nautobot_device_onboarding/venv/lib/python3.6/site-packages/pynautobot/core/response.py", line 386, in save
    if req.patch({i: serialized[i] for i in diff}):
  File "/root/git/pb_nautobot_device_onboarding/venv/lib/python3.6/site-packages/pynautobot/core/query.py", line 350, in patch
    return self._make_call(verb="patch", data=data)
  File "/root/git/pb_nautobot_device_onboarding/venv/lib/python3.6/site-packages/pynautobot/core/query.py", line 226, in _make_call
    raise RequestError(req)
pynautobot.core.query.RequestError: The request failed with code 500 Internal Server Error but more specific details were not returned in json. Check the Nautobot Logs or investigate this exception's error attribute.
>>> my_device.vc_position=1
>>> my_device.virtual_chassis="N5K-SRV-AL01"
>>> my_device.vc_position=1
>>> my_device.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/git/pb_nautobot_device_onboarding/venv/lib/python3.6/site-packages/pynautobot/core/response.py", line 386, in save
    if req.patch({i: serialized[i] for i in diff}):
  File "/root/git/pb_nautobot_device_onboarding/venv/lib/python3.6/site-packages/pynautobot/core/query.py", line 350, in patch
    return self._make_call(verb="patch", data=data)
  File "/root/git/pb_nautobot_device_onboarding/venv/lib/python3.6/site-packages/pynautobot/core/query.py", line 226, in _make_call
    raise RequestError(req)
pynautobot.core.query.RequestError: The request failed with code 500 Internal Server Error but more specific details were not returned in json. Check the Nautobot Logs or investigate this exception's error attribute.
```

Looking at the nautobot logs, I can see some error relate to `django_prometheus/middleware.py`

nautobot log:
```
10:54:07.325 ERROR   django.request :
  Internal Server Error: /api/dcim/devices/2c1422c9-adf8-426d-9450-43aa976c4714/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/utils/deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.7/site-packages/django_prometheus/middleware.py", line 254, in process_request
    content_length = int(request.META.get("CONTENT_LENGTH") or 0)
ValueError: invalid literal for int() with base 10: '53, 53'
[pid: 51|app: 0|req: 204/2258] 10.199.30.3 () {40 vars in 664 bytes} [Wed Feb  2 10:54:07 2022] PATCH /api/dcim/devices/2c1422c9-adf8-426d-9450-43aa976c4714/ => generated 1834 bytes in 2 msecs (HTTP/1.1 500) 8 headers in 245 bytes (1 switches on core 0)
```

**Comment by lvrfrc87** [comment] 2022-02-02 10:58
@chadell FYI

**Comment by jvanderaa** [comment] 2022-02-02 14:21
@lvrfrc87 do you have the REST API call that works on this?

**Comment by nniehoff** [comment] 2022-02-02 14:30
I can't seem to reproduce this on the demo environment.  I'm going to test locally...

**Comment by jmcgill298** [comment] 2022-02-02 16:05
@lvrfrc87 did the above call work? In your code I do not see `vc_priority` being set.

**Comment by lvrfrc87** [comment] 2022-02-02 16:17
Yes, the one above worked. `vc_priority` I understand is optional while `vc_position` is mandatory - pls correct me if I am wrong.

**Comment by jmcgill298** [comment] 2022-02-03 16:23
looks like you d did try with the ID, what happens if you disable django_prometheus?

**Comment by jmcgill298** [comment] 2022-02-03 16:34
how did you test the Rest API outside of pynautobot? Where was that request from?

**Comment by nniehoff** [comment] 2022-02-04 12:37
@lvrfrc87 please confirm you resolved this.  I believe it was an issue caused be their proxy.

**Comment by lvrfrc87** [comment] 2022-02-04 14:32
Yes. Skipping the proxy is now ok. Thanks for your help

**Comment by jvanderaa** [comment] 2022-02-04 15:28
Closing issue for @lvrfrc87

**Closed by jvanderaa** 2022-02-04 15:28 UTC
